-- adding spacesuit to new players
minetest.register_on_newplayer(function(player)
	local inv=player:get_inventory()
	inv:add_item("main","spacesuit:air_gasbottle")
	inv:add_item("main","marssurvive:led 8")
	inv:add_item("main","flowers:geranium 3")
	inv:add_item("main","marssurvive:random_seed 20")
	inv:add_item("main","default:apple 20")
	inv:add_item("main","gas:oxygen 416")
	inv:add_item("main","marsair:airgen")
end)
print("[MOD] mars-pack_initial_items loaded!")
